services:
  spreadsheet_server:
    image: spreadsheet_server
    container_name: spreadsheet_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    volumes:
      - ./spreadsheets:/home/ubuntu/spreadsheet_server/spreadsheets
      - ./saved_spreadsheets:/home/ubuntu/spreadsheet_server/saved_spreadsheets
      - ./log:/home/ubuntu/spreadsheet_server/log
    restart: always
    networks:
        - spreadsheet_server

networks:
  spreadsheet_server:
    name: spreadsheet_server
    driver: bridge
